[versions]

kotlin = "1.6.21"
binarycompatibility = "0.8.0"
compose = "1.2.0-alpha01-dev686"
coroutines = "1.6.0"
datetime = "0.3.1"
immutablecollections = "0.3.4"
juul-indexeddb = "0.2.3"
ktor = "2.0.2"
serialization = "1.3.2"
slf4j = "1.7.21"

[libraries]

coroutines-core-common = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-core-js = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-js", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }

immutablecollections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "immutablecollections" }

juul-indexeddb-core = { module = "com.juul.indexeddb:core", version.ref = "juul-indexeddb" }
juul-indexeddb-external = { module = "com.juul.indexeddb:external", version.ref = "juul-indexeddb" }

ktor-websockets = { module = "io.ktor:ktor-websockets", version.ref = "ktor" }

ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }

ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktor-server-test = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }

serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "serialization" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

turbine = "app.cash.turbine:turbine:0.8.0"

[bundles]

# TODO : Make some Ktor bundles for client and server.
